export default {
    days:['','Saturday 18 August', 'Sunday 19 August', 'Monday 20 August'],
    friday: [],
    saturday:[
        {
            id: 1,
            homeTeam: 'CAR',
            homeLogo: require('./assets/images/premier_league/car.png'),
            homeScore: 0,
            time: '07:30 AM',
            awayTeam: 'NEW',
            awayLogo: require('./assets/images/premier_league/new.png'),
            awayScore: 0,
        },
        {
            id: 2,
            homeTeam: 'EVE',
            homeLogo: require('./assets/images/premier_league/eve.png'),
            homeScore: 2,
            time: '10:00 AM',
            awayTeam: 'SOU',
            awayLogo: require('./assets/images/premier_league/sou.png'),
            awayScore: 1,
        },
        {
            id: 3,
            homeTeam: 'LEI',
            homeLogo: require('./assets/images/premier_league/lei.png'),
            homeScore: 2,
            time: '10:00 AM',
            awayTeam: 'WOL',
            awayLogo: require('./assets/images/premier_league/wol.png'),
            awayScore: 0,
        },
        {
            id: 4,
            homeTeam: 'TOT',
            homeLogo: require('./assets/images/premier_league/tot.png'),
            homeScore: 3,
            time: '10:00 AM',
            awayTeam: 'FUL',
            awayLogo: require('./assets/images/premier_league/ful.png'),
            awayScore: 1,
        },
        {
            id: 5,
            homeTeam: 'WHU',
            homeLogo: require('./assets/images/premier_league/whu.png'),
            homeScore: 1,
            time: '10:00 AM',
            awayTeam: 'BOU',
            awayLogo: require('./assets/images/premier_league/bou.png'),
            awayScore: 2,
        },
        {
            id: 6,
            homeTeam: 'CHE',
            homeLogo: require('./assets/images/premier_league/che.png'),
            homeScore: 3,
            time: '12:30 PM',
            awayTeam: 'ARS',
            awayLogo: require('./assets/images/premier_league/ars.png'),
            awayScore: 2,
        },
    ],
    sunday:[
        {
            id: 7,
            homeTeam: 'BUR',
            homeLogo: require('./assets/images/premier_league/bur.png'),
            homeScore: 0,
            time: '08:30 AM',
            awayTeam: 'WAT',
            awayLogo: require('./assets/images/premier_league/wat.png'),
            awayScore: 0,
        },
        {
            id: 8,
            homeTeam: 'MCI',
            homeLogo: require('./assets/images/premier_league/mci.png'),
            homeScore: 0,
            time: '08:30 AM',
            awayTeam: 'HUD',
            awayLogo: require('./assets/images/premier_league/hud.png'),
            awayScore: 0,
        },
        {
            id: 9,
            homeTeam: 'BHA',
            homeLogo: require('./assets/images/premier_league/bha.png'),
            homeScore: 0,
            time: '11:00 AM',
            awayTeam: 'MUN',
            awayLogo: require('./assets/images/premier_league/mun.png'),
            awayScore: 0,
        },
    ],
    monday: [
        {
            id: 10,
            homeTeam: 'CRY',
            homeLogo: require('./assets/images/premier_league/cry.png'),
            homeScore: 0,
            time: '03:00 PM',
            awayTeam: 'LIV',
            awayLogo: require('./assets/images/premier_league/liv.png'),
            awayScore: 0,
        },
    ],
}