export default {
    days:['','Saturday 18 August', 'Sunday 19 August', 'Monday 20 August'],
    friday: [],
    saturday:[
        {
            id: 1,
            homeTeam: 'CAR',
            homeLogo: require('./assets/images/premier_league/car.png'),
            homeScore: 0,
            time: '07:30 AM',
            awayTeam: 'NEW',
            awayLogo: require('./assets/images/premier_league/new.png'),
            awayScore: 0,
            scorers: [['','Hayden 66 (Red Card)']],
            stats: [
                ['51.3','Possession %','48.7'],
                ['12','Shots','12'],
                ['1','Shots on target','6'],
                ['5','Corners','5'],
                ['14','Fouls','16'],
                ['2','Yellow cards','2'],
                ['0','Red cards','1'],
                ['2','Offsides','0'],
            ],
        },
        {
            id: 2,
            homeTeam: 'EVE',
            homeLogo: require('./assets/images/premier_league/eve.png'),
            homeScore: 2,
            time: '10:00 AM',
            awayTeam: 'SOU',
            awayLogo: require('./assets/images/premier_league/sou.png'),
            awayScore: 1,
            scorers: [['Walcott 15','Ings 54'],['Richarlison 31','']],
            stats: [
                ['57.9','Possession %','42.1'],
                ['13','Shots','15'],
                ['7','Shots on target','4'],
                ['2','Corners','5'],
                ['8','Fouls','20'],
                ['0','Yellow cards','5'],
                ['0','Red cards','0'],
                ['2','Offsides','3'],
            ],
        },
        {
            id: 3,
            homeTeam: 'LEI',
            homeLogo: require('./assets/images/premier_league/lei.png'),
            homeScore: 2,
            time: '10:00 AM',
            awayTeam: 'WOL',
            awayLogo: require('./assets/images/premier_league/wol.png'),
            awayScore: 0,
            scorers: [['Doherty 29 (OG)',''],['Maddison 45',''],['Vardy 66 (Red Card)','']],
            stats: [
                ['42.9','Possession %','57.1'],
                ['6','Shots','11'],
                ['2','Shots on target','3'],
                ['1','Corners','9'],
                ['10','Fouls','8'],
                ['2','Yellow cards','1'],
                ['1','Red cards','0'],
                ['0','Offsides','1'],
            ],
        },
        {
            id: 4,
            homeTeam: 'TOT',
            homeLogo: require('./assets/images/premier_league/tot.png'),
            homeScore: 3,
            time: '10:00 AM',
            awayTeam: 'FUL',
            awayLogo: require('./assets/images/premier_league/ful.png'),
            awayScore: 1,
            scorers: [['Moura 43','Mitrovic 52'],['Trippier 74',''],['Kane 77','']],
            stats: [
                ['59.7','Possession %','40.3'],
                ['25','Shots','10'],
                ['11','Shots on target','3'],
                ['5','Corners','2'],
                ['9','Fouls','5'],
                ['0','Yellow cards','0'],
                ['0','Red cards','0'],
                ['1','Offsides','3'],
            ],
        },
        {
            id: 5,
            homeTeam: 'WHU',
            homeLogo: require('./assets/images/premier_league/whu.png'),
            homeScore: 1,
            time: '10:00 AM',
            awayTeam: 'BOU',
            awayLogo: require('./assets/images/premier_league/bou.png'),
            awayScore: 2,
            scorers: [['Arnautovic 33 (Pen)','Wilson 60'],['','Cook 66']],
            stats: [
                ['60.9','Possession %','39.1'],
                ['11','Shots','12'],
                ['5','Shots on target','5'],
                ['6','Corners','4'],
                ['14','Fouls','10'],
                ['6','Yellow cards','2'],
                ['0','Red cards','0'],
                ['1','Offsides','0'],
            ],
        },
        {
            id: 6,
            homeTeam: 'CHE',
            homeLogo: require('./assets/images/premier_league/che.png'),
            homeScore: 3,
            time: '12:30 PM',
            awayTeam: 'ARS',
            awayLogo: require('./assets/images/premier_league/ars.png'),
            awayScore: 2,
            scorers: [['Pedro 9','Mkhitaryan 37'],['Morata 20','Iwobi 41'],['Alonso 81','']],
            stats: [
                ['62.3','Possession %','37.7'],
                ['24','Shots','15'],
                ['11','Shots on target','6'],
                ['5','Corners','1'],
                ['12','Fouls','9'],
                ['0','Yellow cards','2'],
                ['0','Red cards','0'],
                ['3','Offsides','3'],
            ],
        },
    ],
    sunday:[
        {
            id: 7,
            homeTeam: 'BUR',
            homeLogo: require('./assets/images/premier_league/bur.png'),
            homeScore: 0,
            time: '08:30 AM',
            awayTeam: 'WAT',
            awayLogo: require('./assets/images/premier_league/wat.png'),
            awayScore: 0,
        },
        {
            id: 8,
            homeTeam: 'MCI',
            homeLogo: require('./assets/images/premier_league/mci.png'),
            homeScore: 0,
            time: '08:30 AM',
            awayTeam: 'HUD',
            awayLogo: require('./assets/images/premier_league/hud.png'),
            awayScore: 0,
        },
        {
            id: 9,
            homeTeam: 'BHA',
            homeLogo: require('./assets/images/premier_league/bha.png'),
            homeScore: 0,
            time: '11:00 AM',
            awayTeam: 'MUN',
            awayLogo: require('./assets/images/premier_league/mun.png'),
            awayScore: 0,
        },
    ],
    monday: [
        {
            id: 10,
            homeTeam: 'CRY',
            homeLogo: require('./assets/images/premier_league/cry.png'),
            homeScore: 0,
            time: '03:00 PM',
            awayTeam: 'LIV',
            awayLogo: require('./assets/images/premier_league/liv.png'),
            awayScore: 0,
        },
    ],
}